name: 2.1 CI in Github Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - enh/issue#7/ci-in-github

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12

      - name: Create conda environment from env.yaml
        run: conda env create -f env.yaml
        shell: bash -l {0}

      - name: Activate conda environment
        run: |
          conda init
          conda activate mle-dev
        shell: bash -l {0}

      - name: Run flake8
        run: flake8 nonstandardcode.py
        shell: bash -l {0}

      - name: Run logic
        run: python nonstandardcode.py
        shell: bash -l {0}
