name: 2.2 Build Package

on:
  push:
    branches:
      - enh/issue#9/python-packaging

jobs:
  build-and-upload-artifact-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: mle-dev
          environment-file: env.yaml

      - name: List installed libraries
        run: conda list
        shell: bash -l {0}

      - name: Run flake8
        run: |
          flake8 src/house_price_prediction/nonstandardcode.py
        shell: bash -l {0}

      - name: Update apt-get packages
        run: sudo apt-get update

      - name: Install tree CLI tool
        run: sudo apt-get install -y tree

      - name: Display directory tree before building
        run: tree

      - name: Upgrade the build package
        run: python -m pip install --upgrade build

      - name: Build the package
        run: python -m build

      - name: Display directory tree after building
        run: tree

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  download-artifact-and-install-package-job:
    runs-on: ubuntu-latest
    needs: build-and-upload-artifact-job
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Update apt-get packages
        run: sudo apt-get update

      - name: Install tree CLI tool
        run: sudo apt-get install -y tree

      - name: Display directory tree before building
        run: tree

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: mle-dev
          environment-file: env.yaml

      - name: Install the package
        run: pip install dist/house_price_prediction-0.1.0-py3-none-any.whl

      - name: Run package
        run: python running_the_package.py
