name: 2.3 Testing Python Code

on:
  push:
    branches:
      - test/issue#11/testing-python-package

jobs:
  test-package-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: mle-dev
          environment-file: env.yaml

      - name: Run flake8
        run: |
          flake8 src/house_price_prediction/nonstandardcode.py
        shell: bash -l {0}

      - name: Update apt-get packages
        run: sudo apt-get update

      - name: Install tree CLI tool
        run: sudo apt-get install -y tree

      - name: Display directory tree before building
        run: tree

      - name: Upgrade the build package
        run: python -m pip install --upgrade build

      - name: Build the package
        run: python -m build

      - name: Display directory tree after building
        run: tree

      - name: Install the custom package
        run: pip install dist/house_price_prediction-0.1.0-py3-none-any.whl

      - name: Install pytest
        run: conda install -n mle-dev pytest

      - name: Running pytest for testing
        run : python -m pytest

