name: 2.4 Refactoring Code

on:
  push:
    branches:
      - enh/issue#13/refactoring-code

jobs:
  test-package-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: mle-dev
          environment-file: env.yaml

      - name: Update apt-get packages
        run: sudo apt-get update

      - name: Install tree CLI tool
        run: sudo apt-get install -y tree

      - name: Display directory tree before building
        run: tree

      - name: Upgrade the build package
        run: python -m pip install --upgrade build

      - name: Build the package
        run: python -m build

      - name: Display directory tree after building
        run: tree

      - name: Install the custom package
        run: pip install dist/house_price_prediction-0.2.0-py3-none-any.whl

      - name: Running pytest for testing
        run : pytest

